# In this notebook, we are going to cover some of the most fundamental concepts of tensors using Tensorflow

More specifically, we're going to cover:
- Introduction to Tensors
- Getting information from Tensors
- Manipulating Tensors
- Tensors and Numpy
- Using @tf.function (a way to speed up your regular functions)
- Using GPUs with Tensorflow (or TPUs)
- Exercises to try for yourself


## Introduction to Tensors

In [1]:
# Import Tensorflow
import tensorflow as tf

# version of tensor
print(tf.__version__)

2.13.0


In [2]:
# Create Tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

> NOTE: for docstring press command + shift + space

In [3]:
# dimension of scalar
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([1, 2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [5]:
# dimension of vector
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant([
    [1, 2],
    [3, 4]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
# dimension of matrix
matrix.ndim

2

In [8]:
another_matrix = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

another_matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [9]:
another_matrix.ndim

2

In [10]:
# Create a tensor
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
# dimension of a tensor
tensor.ndim

3

In [12]:
# tensor with datatype as float
tensor_2 = tf.constant([
    [
        [1., 2., 3.],
        [4., 5., 6.]
    ],
    [
        [7., 8., 9.],
        [10., 11., 12.]
    ],
    [
        [13., 14., 15.],
        [16., 17., 18.]
    ]
], dtype=tf.float16)

tensor_2

<tf.Tensor: shape=(3, 2, 3), dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]], dtype=float16)>

In [13]:
tensor_2.ndim

3

### What we've created so far:
* Scalar - a single number
* Vector - a number with direction (wind speed and direction)
* Matrix - a 2 dimensional array of numbers
* Tensor - an n-dimensional array of numbers (

### Creating tensors with `tf.Variable`
- We can change the value of a variable tensor

In [14]:
changeable_tensor = tf.Variable([10, 7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [15]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

## Creating random tensors

In [16]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the order of elements in a tensor
🔔 A nice use case can be, let's say you have a tensor and its learning on some data and the data is in order. You have 2 class of images: pizza and burger. If there is 1000 total images and you have 800 images of pizza in order, then the neural net will adjust mostly according to pizza. To get rid of this problem, a shuffle is good to make the model learn uniformly.


In [17]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

# shuffle this tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [18]:
# shuffle with a seed, which will produce same result
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

## Other ways to make tensors

In [19]:
# create a tensor of all ones
tensor_1 = tf.ones(shape=(3, 4), dtype=tf.int32)
tensor_1

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [20]:
# create a tensor of all zeros
tensor_2 = tf.zeros(shape=(3, 4), dtype=tf.float16)
tensor_2

<tf.Tensor: shape=(3, 4), dtype=float16, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)>

## Turn NumPy array into Tensors

🔔 This is useful because with tensors you can use GPU which is much faster for numerical computing

In [21]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
# Convert numpy to tensor
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)

A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

## Getting information from tensors

|Attribute| Meaning | Code |
|---------|---------|------|
|Shape|The length (number of elements) of each of the dimensions of a tensor| tensor.shape|
|Rank | The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix has rank 2, a tensor has rank n| tensor.ndim|
|Axis or dimension| A particular dimension of a tensor| tensor[0], tensor[:, 1] |
|Size | The total number of items in the tensor | tf.size(tensor) |

In [23]:
# Create a rank 4 tensor ( 4 dimensions )

rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
def get_tensor_attributes(temp_tensor):
  print("Datatype of every element: ", temp_tensor.dtype)
  print("Shape: ", temp_tensor.shape)
  print("Rank: ", temp_tensor.ndim)
  print("Axis or dimension with first dimension: ", temp_tensor[0])
  # print("Axis or dimension with single column: ", temp_tensor[:, 1])
  print("Size of the tensor: ", tf.size(temp_tensor))
  print("Size of the tensor in just number: ",tf.size(temp_tensor).numpy())

In [25]:
get_tensor_attributes(rank_4_tensor)

Datatype of every element:  <dtype: 'float32'>
Shape:  (2, 3, 4, 5)
Rank:  4
Axis or dimension with first dimension:  tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Size of the tensor:  tf.Tensor(120, shape=(), dtype=int32)
Size of the tensor in just number:  120


## Indexing Tensors

Tensors can be indexed just like python lists

In [26]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([
    [1, 2],
    [3, 4]
])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [29]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [30]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [31]:
# Another approach to add dimension
tf.expand_dims(rank_2_tensor, axis=-1) # adding axis at end

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

## Manipulating tensors (tensor operations)

**Basic operations**
`+`, `-`, `*`, `/`

In [32]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[1, 2], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [33]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [34]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [35]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 1. ],
       [1.5, 2. ]])>

In [36]:
# We can also use built-in functions
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [37]:
# the tensor remains unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

## Matrix Multiplication

In machine learning, matrix multiplication is one of the most common tensor operations

In [38]:
# matrix mutliplication
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [39]:
# python operation to do this is @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

**The dot product **
Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* tf.matmul()
* tf.tensordot()

## Changing the datatype of a tensor

In [40]:
# Create a tensor
B = tf.constant([10., 7.])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>

In [41]:
# Convert float32 to float 16
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([10.,  7.], dtype=float16)>

## Aggregating tensors

In [42]:
# Get the absolute values
C = tf.constant([-7, -10])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [43]:
tf.abs(C)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Let's go through the following forms of aggregation
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [44]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 4, 33, 75, 35, 46, 44, 14, 85, 15, 60, 16, 89, 78, 15, 60,  3,  0,
       82, 51, 68, 98, 87,  2, 49, 74, 73, 51,  0, 58, 76, 45,  2, 88, 99,
       63, 36, 26, 74, 55, 52, 42, 10, 77, 51, 39, 20, 47, 59, 81, 65])>

In [45]:
get_tensor_attributes(E)

Datatype of every element:  <dtype: 'int64'>
Shape:  (50,)
Rank:  1
Axis or dimension with first dimension:  tf.Tensor(4, shape=(), dtype=int64)
Size of the tensor:  tf.Tensor(50, shape=(), dtype=int32)
Size of the tensor in just number:  50


In [46]:
import tensorflow_probability as tfp

In [47]:
def get_tensor_aggregates(temp):
  print("Minimum: ", tf.reduce_min(temp))
  print("Maximum: ", tf.reduce_max(temp))
  print("Mean: ", tf.reduce_mean(temp))
  print("Sum: ", tf.reduce_sum(temp))
  # print("Variance: ", tfp.stats.variance(temp))
  print("Variance: ", tf.math.reduce_variance(tf.cast(temp, dtype=tf.float32)))
  print("Standard Deviation: ", tf.math.reduce_std(tf.cast(temp, dtype=tf.float32)))


In [48]:
get_tensor_aggregates(E)

Minimum:  tf.Tensor(0, shape=(), dtype=int64)
Maximum:  tf.Tensor(99, shape=(), dtype=int64)
Mean:  tf.Tensor(49, shape=(), dtype=int64)
Sum:  tf.Tensor(2472, shape=(), dtype=int64)
Variance:  tf.Tensor(814.3264, shape=(), dtype=float32)
Standard Deviation:  tf.Tensor(28.536406, shape=(), dtype=float32)


## Find the positional minimum and maximum of a tensor

In [49]:
# Create a new tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [50]:
# Find the positional maximum
tf.argmax(F).numpy()

42

In [51]:
# The value
F[tf.argmax(F)].numpy()

0.9671384

In [52]:
# Find the positional minimum
tf.argmin(F).numpy()

16

In [53]:
F[tf.argmin(F)].numpy()

0.009463668

### Squeezing a tensor (removing all single dimensions)

In [54]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G, G.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [55]:
# Squeezing
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [56]:
# create a list of indices
indices = [0, 1, 2, 3, 4]
# one hot encode
tf.one_hot(indices, depth=4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [57]:
# specify custom values for one hot encoding
tf.one_hot(indices, depth=5, on_value="True", off_value="False")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'True', b'False', b'False', b'False', b'False'],
       [b'False', b'True', b'False', b'False', b'False'],
       [b'False', b'False', b'True', b'False', b'False'],
       [b'False', b'False', b'False', b'True', b'False'],
       [b'False', b'False', b'False', b'False', b'True']], dtype=object)>

## Finding access to GPU

In [58]:
# List physical devices
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [65]:
# is there a GPU available
def isGPURunning():
  if tf.config.list_physical_devices("GPU"):
    return "Yes"
  return "No"

In [64]:
isGPURunning()

'No'

after enabling GPU

In [66]:
isGPURunning()

'Yes'

In [67]:
# what type of GPU you are using
!nvidia-smi

Mon Oct  9 06:29:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0    27W /  70W |    361MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------